name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file an issue. Here are some tips:

        - Please only use issues for bug reports and feature requests. If you need help with Elvish, the user group (linked from the repo README) is a more suitable place.
        - Please search existing issues to see if the same or similar report has been filed before.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened, and what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        Only bugs affecting the latest release or the latest development versions will be fixed. You can still file an issue if you are running an older version, but the issue will be closed if it's already been addressed.

        You can find out Elvish's version by running `elvish -version`.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow Elvish's [Code of Conduct](https://src.elv.sh/CODE_OF_CONDUCT.md).
          required: true
